seed = 0
parent_dir = "configs/intrusion"
model_save_path = "ckpt/intrusion"
sample_save_path = "sampled/intrusion"
real_data_path = "Data/intrusion"
task_type= "binclass"
model_type = "mlp"

[model_params]
d_in = 40
num_classes = 2
is_y_cond = true

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"

[sample]
num_samples = 5000
batch_size = 500
seed = 0

[model_params.rtdl_params]
d_layers = [ 128, 512,]
dropout = 0.0

[train.main]
steps = 30000
lr = 1.1510940031144828e-5
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
